// react/src/components/RegisterComponent.js
import React from 'react';
import ReactDom from 'react-dom';

 
export default class LonginComponent extends React.Component {
	constructor(props) {
	  super(props);
	
	  this.state = {};
	}

    componentDidMount(){
         
    }

	render() {
		return (
			<div className="rightBox" id="registerBox">
	            <div className="title"><span>注册</span></div>
	            <div className="line"><span className="colDark">用户名：</span><input type="text" name="username" /></div>
	            <div className="line"><span className="colDark">密码：</span><input type="password" name="password" /></div>
	            <div className="line"><span className="colDark">确认：</span><input type="password" name="repassword" /></div>
	            <div className="line"><span className="colDark"></span>
	                <button>注 册</button>
	            </div>
	            <p className="textRight">已有账号？<a href="javascript:;" className="colMint">马上登录</a></p>
	            <p className="colWarning textCenter"></p>
	        </div>
		)
	}
}

// angular/src/app/components/register/register.component.ts
import { Component, EventEmitter, Output } from '@angular/core';

@Component({
  selector: 'blog-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent {
   @Output() toggleFun = new EventEmitter();
   
   constructor() {

   }
   
   toggle(value) {
      this.toggleFun.emit(value);
   }

}

<div class="rightBox" id="registerBox">
    <div class="title"><span>注册</span></div>
    <div class="line"><span class="colDark">用户名：</span><input type="text" name="username"></div>
    <div class="line"><span class="colDark">密码：</span><input type="password" name="password"></div>
    <div class="line"><span class="colDark">确认：</span><input type="password" name="repassword"></div>
    <div class="line"><span class="colDark"></span>
        <button>注 册</button>
    </div>
    <p class="textRight">已有账号？<span class="colMint" (click)="toggle('login')">马上登录</span></p>
    <p class="colWarning textCenter"></p>
</div>
