// react/src/components/UserComponent.js
import React from 'react';
import { Link } from 'react-router-dom';
import $axios from '../utils';
export default class UserComponent extends React.Component {
	constructor(props) {
	  super(props);
	
	  this.state = {
      
    };
	}

  componentDidMount(){
       
  }
   
  loginOutHandle() {
     let _this = this;
     $axios.get('/logout').then((res)=>{
         this.props.Logout();
     }).catch(()=>{
      
     });
  }

	render() {
    
		return (
			 <div className="rightBox">
          <div className="title"><span>用户信息</span></div>
          <p><span className="colDark">Fantaghiro</span></p>
          <p>
              <span className="colDanger">你好，管理员！</span>
              <Link to="/admin">进入管理</Link>
          </p>

          <p><span className="colDanger">你好，欢迎光临我的博客！</span></p>

          <p><span className="colDark loginout" onClick={this.loginOutHandle.bind(this)}>退出</span></p>
       </div>
		)
	}
}

// angular/src/app/components/user/user.component.ts
import { Component, EventEmitter, Output } from '@angular/core';

@Component({
  selector: 'blog-user',
  templateUrl: './user.component.html',
  styleUrls: ['./user.component.css']
})
export class UserComponent {
	@Output() logout = new EventEmitter();
	constructor() {

	}
	logoutHandle() {
       this.logout.emit();
	}
}

<div class="rightBox" id="userInfo">
    <div class="title"><span>用户信息</span></div>
    <p><span class="colDark">Fantaghiro</span></p>

    <p>
        <span class="colDanger">你好，管理员！</span>
        <a href="/admin">进入管理</a>
    </p>

    <p><span class="colDanger">你好，欢迎光临我的博客！</span></p>

    <p><span class="colDark"><a href="javascript:void(0);" (click)="logoutHandle()" id="logout">退出</a></span></p>
</div>
